import Head from 'next/head';
import { useState, useRef } from 'react';
import Link from 'next/link'
import styles from '@/styles/Home.module.css';



function Alert(props){
  const {show, close} = props
  return <>
    <div className={`${styles.lightBox} ${show? styles.show:''}`}>
      <div className={styles.tip}>Please enter text</div>
      <div className={styles.ok} onClick={close}>OK</div>
    </div>
  </>
  // fragment
}

function Li({val,remove}) {
  return <>
    <li>{val}<div className={styles.remove} onClick={remove}>✖</div></li>
  </>
}

export default function Home() {
  const [ inputValue, setInputValue] = useState(0);
  const [ items, setItems ] = useState([]);
  const [ showAlert, setShowAlert ] = useState('');
  const inputRef = useRef(null);
  
  function handleButtonDisplay(e) {
    const {value} = e.target;
    setInputValue(value);
    
  }

  function handleItemsAdd() {
    if(inputValue.trim()){
      // setItems(prevItems => [...prevItems, <li key={prevItems.length}>{inputValue}<div className={styles.remove}>✖</div></li>]);
      // inputRef.current.value = "";
      setItems(prevItems => [...prevItems, <Li key={prevItems.length + 1} val={inputValue} remove={handleItemsRemove}></Li>]);
      inputRef.current.value = "";
      setInputValue('');
    }else{
      setShowAlert(true);
      inputRef.current.value = "";
    };
  }

  function lightBoxClose() {
    setShowAlert(false);
  }

  function handleItemsRemove() {
    //沒有更新items??
    setItems(items);
    console.log(items);


    // setItems(prevItems => [...prevItems, <li key={prevItems.length}>{inputValue}<div className={styles.remove}>✖</div></li>])
  }

  function HandlelightBox() {

  }

  return (
    <>
      <Head>
        <title>My Todos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Sono:wght@300;400;600&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>My Todos</h1>
        <div className={styles.add_todo}>
          <input className={styles.add_input} onChange={handleButtonDisplay} ref={inputRef}></input>
          <div className={styles.add_button} style={inputValue.length > 0 ? {'transform': 'scale(1)','width':'50px','height':'50px','opacity':'1'}:{}} onClick={handleItemsAdd}><p>+</p></div>
        </div>
        <div className={styles.list}>
          <ul className={styles.list_scroll}>
            <Li val='3/14: learn next.js' remove={handleItemsRemove} />
            {items}

          </ul>
        </div>
        <Alert show={showAlert} close={lightBoxClose} />
        {/* <div className={`${styles.lightBox} ${showAlert? styles.show:''}`}>
          <div className={styles.tip}>Please enter text</div>
          <div className={styles.ok} onClick={lightBoxClose}>OK</div>
        </div> */}
      </main>
    </>
  )
}
